#!/bin/bash

# RSP 2015-02-19
# ajax-cdn-speed-test
# https://github.com/rsp/ajax-cdn-speed-test
# by Rafał Pocztarski https://rsp.github.io/

urls="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js \
      //ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.3.min.js \
      //code.jquery.com/jquery-2.1.3.min.js \
      //yastatic.net/jquery/2.1.3/jquery.min.js \
      //cdn.jsdelivr.net/jquery/2.1.3/jquery.min.js \
      //cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"

pings=5
interval=0.2

for url in $urls
do
    echo -e "\n$url"
	for protocol in http https
	do
	    purl="$protocol:$url"
	    curl -Lo /dev/null -skw "$protocol download:\t%{time_total}s\n" $purl
	done
	host=`echo $url | cut -d/ -f3`
	avgping=`ping -c $pings -i $interval $host | tail -1 | cut -d/ -f 5`
    echo -e "average ping:\t$avgping"
done

