#!/bin/bash

# RSP 2015-02-19
# CDN speed test by Rafał Pocztarski https://rsp.github.io/

urls="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js \
      //ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.3.min.js \
      //cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"

protocol=http
pings=5
interval=0.2
# curlstats="connect: %{time_connect}s\n\
# namelookup: %{time_namelookup}s\n\
# pretransfer: %{time_pretransfer}\n\
# starttransfer: %{time_starttransfer}s\n\
# redirect: %{time_redirect}s\n\
# total: %{time_total}s\n"
curlstats="total download: %{time_total}s\n"

for url in $urls
do
	host=`echo $url | cut -d/ -f3`
    purl="$protocol:$url"
    echo -e "\n$purl"
    curl -Lo /dev/null -skw "$curlstats" $purl
	avgping=`ping -c $pings -i $interval $host | tail -1 | cut -d/ -f 5`
    echo "average ping: $avgping"
done

